services:
  java:
    image: bitnami/java
    container_name: java-app
    working_dir: /app
    command: "sleep infinity"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=adminpass
      - POSTGRESQL_DATABASE=tareas_db
    ports:
      - "5431:5432"

    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
